services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: abhi763153
      POSTGRES_PASSWORD: "abhi763153"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "abhishekkamat724@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Abhi$$hek123"
      PGADMIN_CONFIG_SERVER: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80" 
    networks:
      - postgres
    restart: unless-stopped
  config-server-ms:
    build:
      context: ./Config-Server
    image: abhi763153d/config-server
    container_name: config-server
    ports: 
      - "50760:50760"
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  service-reg:
    build:
      context: ./service-reg
    image: abhi763153d/service-reg
    container_name: service-reg
    ports: 
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres
  companyms:
    build:
      context: ./CompanyMS
    image: abhi763153d/companyms
    container_name: companyms
    ports: 
      - "64525:64525"
      - "5008:5008"    # debug port
    depends_on:
      - postgres
      - service-reg
      - config-server-ms
      - zipkin
      - rabbitmq
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka
  jobms:
    build:
      context: ./JobMS
    image: abhi763153d/jobms
    container_name: jobms
    ports: 
      - "64529:64529"
      - "5007:5007"    # debug port
    depends_on:
      - postgres
      - service-reg
      - config-server-ms
      - zipkin
      - rabbitmq
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka
  reviewms:
    build:
      context: ./ReviewMS
    image: abhi763153d/reviewms
    container_name: reviewms
    ports: 
      - "64536:64536"
      - "5006:5006"    # debug port
    depends_on:
      - postgres
      - service-reg
      - config-server-ms
      - zipkin
      - rabbitmq
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice-network
      - postgres
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
  gateway-ms:
    build:
      context: ./gateway
    image: abhi763153d/gateway
    ports: 
      - "64539:64539"
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker


volumes:
  postgres:
  pgadmin:

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge